/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form Menu
     */
    private String namaFrame;
    
    public Menu() {
        initComponents();
        setPanelDokter();
        this.namaFrame = "Dokter";
    }
    
    public void setPanelDokter(){
        mainPanel.removeAll();
        mainPanel.setLayout(new GridLayout(0, 1));
        try{
            Connection a = Koneksi.getKoneksi();
            Statement s = a.createStatement();
            String sql = "SELECT * FROM dokter";
            ResultSet res = s.executeQuery(sql);
            while(res.next())
            {
                Object[] baris = new Object[1];
                baris[0] = res.getInt("id_dokter");
                mainPanel.add(new Dokter((int) baris[0]));
            }
        }
        catch(Exception ex){
            System.out.println(ex);
        }
        
        mainPanel.revalidate();
        mainPanel.repaint();
        this.namaFrame = "Dokter";
    }
    
    public void setPanelSpesialis(){
        mainPanel.removeAll();
        mainPanel.setLayout(new GridLayout(0, 1));
        try{
            Connection a = Koneksi.getKoneksi();
            Statement s = a.createStatement();
            String sql = "SELECT * FROM spesialis";
            ResultSet res = s.executeQuery(sql);
            while(res.next())
            {
//                System.out.println("Gagals");
                Object[] baris = new Object[1];
                baris[0] = res.getInt("id_spesialis");
                mainPanel.add(new Spesialis((int) baris[0]));
            }
        }
        catch(Exception ex){
//            System.out.println("Gagal");
            System.out.println(ex);
        }
        
        mainPanel.revalidate();
        mainPanel.repaint();
        this.namaFrame = "Spesialis";
    }
    
//    public void setData(String nama, )
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonDokter = new javax.swing.JButton();
        ButtonSpesialis = new javax.swing.JButton();
        ButtonAddData = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ButtonDokter.setText("Dokter");
        ButtonDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDokterActionPerformed(evt);
            }
        });

        ButtonSpesialis.setText("Spesialis");
        ButtonSpesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSpesialisActionPerformed(evt);
            }
        });

        ButtonAddData.setText("Tambah");
        ButtonAddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddDataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setText("Data Klinik TongFang");

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(ButtonDokter)
                            .addGap(98, 98, 98)
                            .addComponent(ButtonSpesialis)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonAddData)
                            .addGap(274, 274, 274))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDokter)
                    .addComponent(ButtonSpesialis)
                    .addComponent(ButtonAddData))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSpesialisActionPerformed
        // TODO add your handling code here:
        setPanelSpesialis();
    }//GEN-LAST:event_ButtonSpesialisActionPerformed

    private void ButtonAddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddDataActionPerformed
        // TODO add your handling code here:
        if(this.namaFrame.equals("Dokter")){
            dispose();
            TambahDokter c = new TambahDokter();
            c.setVisible(true);
            c.pack();
            c.setLocation(null);
            c.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        }
        else if(this.namaFrame.equals("Spesialis")){
            dispose();
            TambahSpesialis c = new TambahSpesialis();
            c.setVisible(true);
            c.pack();
            c.setLocation(null);
            c.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_ButtonAddDataActionPerformed

    private void ButtonDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDokterActionPerformed
        // TODO add your handling code here:
         setPanelDokter();
    }//GEN-LAST:event_ButtonDokterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddData;
    private javax.swing.JButton ButtonDokter;
    private javax.swing.JButton ButtonSpesialis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
